### ISSUE TITLE
ZK temp directory doesn't have sufficient permissions 

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/ece-support-diagnostics#58]
I'm really not sure if this is a bug, or PEBKAC

Running using the -zk option , e.g:
`./diagnostics.sh -s -d -a --zookeeper ~/andy.hunt.public.key  -u admin -p $PASS -zk-path /`

The zookeeper part of the script creates a temporary directory: `zookeeper_cleartext_folder=$(mktemp -d $elastic_folder/../zookeeper_dump_temporary.XXXX)`

But when the docker command to extract the ZK info runs, it cannot access the temp directory:
```
Dump failed: /target/zkdump.zip (Permission denied)
java.io.FileNotFoundException: /target/zkdump.zip (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at no.found.shell.utils.TreeTools$$anonfun$6.apply(TreeTools.scala:239)
        at no.found.shell.utils.TreeTools$$anonfun$6.apply(TreeTools.scala:239)
        at scala.util.Try$.apply(Try.scala:192)
        at no.found.shell.utils.TreeTools$.dumpZookeeperContents(TreeTools.scala:239)
        at no.found.shell.utils.TreeTools$ZkPathDumpSyntax$$anon$3.<init>(TreeTools.scala:265)
        at no.found.shell.utils.TreeTools$ZkPathDumpSyntax$.dumpInto$extension(TreeTools.scala:262)
        at ammonite.$file.scripts.dumpZkContents$.main(dumpZkContents.sc:39)
        at ammonite.$file.scripts.dumpZkContents$$routes$$anonfun$apply$4.apply(dumpZkContents.sc:58)
        at ammonite.$file.scripts.dumpZkContents$$routes$$anonfun$apply$4.apply(dumpZkContents.sc:58)
        at ammonite.main.Router$EntryPoint.invoke(Router.scala:150)
        at ammonite.main.Scripts$.runMainMethod(Scripts.scala:194)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.apply(Scripts.scala:106)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.apply(Scripts.scala:93)
        at ammonite.util.Util$.withContextClassloader(Util.scala:16)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1$$anonfun$apply$3.apply(Scripts.scala:92)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1$$anonfun$apply$3.apply(Scripts.scala:67)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1.apply(Scripts.scala:67)
        at ammonite.main.Scripts$$anonfun$runScript$1$$anonfun$apply$1.apply(Scripts.scala:46)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.main.Scripts$$anonfun$runScript$1.apply(Scripts.scala:46)
        at ammonite.main.Scripts$$anonfun$runScript$1.apply(Scripts.scala:42)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.main.Scripts$.runScript(Scripts.scala:42)
        at no.found.shell.ShellBootstrap.<init>(ShellBootstrap.scala:240)
        at no.found.shell.ShellBootstrap$.<init>(ShellBootstrap.scala:257)
        at no.found.shell.ShellBootstrap$.<clinit>(ShellBootstrap.scala)
        at no.found.shell.ShellBootstrap.main(ShellBootstrap.scala)
```

I suspect the problem is to do with the user I'm running the script as, but either way, we should note in the instructions what is neccessary.

Workaround - I created a directory `/ahtest`, then `chmod 777 ahtest` then edited the script to set `zookeeper_cleartext_folder=/ahtest`

**Comment by crisdarocha** [comment]
Bumped into the same issue here. Thanks @AndyHunt66
